import os

movies_data = [
    {
        "todo_title": "ロード・オブ・ザ・リング/旅の仲間",
        "title": "ロード・オブ・ザ・リング/旅の仲間",
        "original_title": "The Lord of the Rings: The Fellowship of the Ring",
        "filename": "TheLordOfTheRingsTheFellowshipOfTheRing.md",
        "director": "ピーター・ジャクソン",
        "country": "ニュージーランド, アメリカ",
        "release_year": 2001,
        "genre": ["ファンタジー", "アドベンチャー"],
        "rating_child": 3,
        "has_sexual_content": False,
        "has_violence": True,
        "sf_rating": 1,
        "synopsis": "闇の冥王サウロンが作った「一つの指輪」を手にしたホビットのフロド。世界を滅ぼす力を持つこの指輪を破壊するため、魔法使いのガンダルフや仲間たちと共に、滅びの山を目指す旅に出る。",
        "recommendation": "壮大な冒険物語にドキドキ！小さなホビットが大きな使命に挑む姿に勇気をもらえる。",
        "content_warning": "オークなどの怪物が怖かったり、戦いのシーンが激しい。",
        "sf_review": "剣と魔法のファンタジー。SF要素はない。"
    },
    {
        "todo_title": "バック・トゥ・ザ・フューチャー",
        "title": "バック・トゥ・ザ・フューチャー",
        "original_title": "Back to the Future",
        "filename": "BackToTheFuture.md",
        "director": "ロバート・ゼメキス",
        "country": "アメリカ",
        "release_year": 1985,
        "genre": ["SF", "アドベンチャー", "コメディ"],
        "rating_child": 5,
        "has_sexual_content": False,
        "has_violence": False,
        "sf_rating": 5,
        "synopsis": "高校生のマーティは、友人の科学者ドクが作ったタイムマシン・デロリアンに乗って30年前にタイムスリップしてしまう。そこで若き日の両親に出会い、恋のキューピッド役を務めることに。",
        "recommendation": "ハラハラドキドキの展開が楽しい！タイムトラベルの面白さが詰まっている。",
        "content_warning": "特になし。",
        "sf_review": "タイムマシンのデロリアンがかっこいい。タイムパラドックスを扱ったSFの傑作。"
    },
    {
        "todo_title": "ジュラシック・パーク",
        "title": "ジュラシック・パーク",
        "original_title": "Jurassic Park",
        "filename": "JurassicPark.md",
        "director": "スティーヴン・スピルバーグ",
        "country": "アメリカ",
        "release_year": 1993,
        "genre": ["SF", "アドベンチャー", "パニック"],
        "rating_child": 3,
        "has_sexual_content": False,
        "has_violence": True,
        "sf_rating": 4,
        "synopsis": "バイオテクノロジーで恐竜を現代に蘇らせたテーマパーク「ジュラシック・パーク」。オープン前に招待されたグラント博士たちは、恐竜たちの暴走に巻き込まれ、島からの脱出を試みる。",
        "recommendation": "本物みたいな恐竜が大迫力！",
        "content_warning": "恐竜が人を襲うシーンが怖い。血が出る描写もある。",
        "sf_review": "クローン技術による恐竜の再生というSF設定がリアル。生命倫理への問いかけもある。"
    },
    {
        "todo_title": "E.T.",
        "title": "E.T.",
        "original_title": "E.T. the Extra-Terrestrial",
        "filename": "ET.md",
        "director": "スティーヴン・スピルバーグ",
        "country": "アメリカ",
        "release_year": 1982,
        "genre": ["SF", "ファンタジー", "ドラマ"],
        "rating_child": 5,
        "has_sexual_content": False,
        "has_violence": False,
        "sf_rating": 5,
        "synopsis": "地球に取り残された宇宙人E.T.と、10歳の少年エリオットの友情を描いた物語。エリオットはE.T.を家に匿い、故郷の星へ帰そうと奮闘する。",
        "recommendation": "E.T.とエリオットの友情に感動。自転車で空を飛ぶシーンは名場面。",
        "content_warning": "特になし。",
        "sf_review": "友好的な宇宙人との交流を描いたSFファンタジー。"
    },
    {
        "todo_title": "アバター",
        "title": "アバター",
        "original_title": "Avatar",
        "filename": "Avatar.md",
        "director": "ジェームズ・キャメロン",
        "country": "アメリカ",
        "release_year": 2009,
        "genre": ["SF", "アクション", "アドベンチャー"],
        "rating_child": 4,
        "has_sexual_content": False,
        "has_violence": True,
        "sf_rating": 5,
        "synopsis": "22世紀、人類は惑星パンドラの希少鉱石を求めていた。元海兵隊員のジェイクは、先住民族ナヴィの肉体（アバター）を使って彼らと接触する任務に就くが、次第にナヴィの文化に魅了されていく。",
        "recommendation": "美しいパンドラの森や空飛ぶ生き物たちの映像がすごい！",
        "content_warning": "戦闘シーンがある。",
        "sf_review": "異星の生態系やアバター技術など、ハードSF的な設定と壮大なビジュアルが融合。"
    },
    {
        "todo_title": "インセプション",
        "title": "インセプション",
        "original_title": "Inception",
        "filename": "Inception.md",
        "director": "クリストファー・ノーラン",
        "country": "アメリカ, イギリス",
        "release_year": 2010,
        "genre": ["SF", "アクション", "サスペンス"],
        "rating_child": 2,
        "has_sexual_content": False,
        "has_violence": True,
        "sf_rating": 5,
        "synopsis": "人の夢に入り込み、アイデアを盗み出す産業スパイのコブ。彼は「インセプション」と呼ばれる、相手の無意識にアイデアを植え付けるという困難なミッションに挑む。",
        "recommendation": "夢の中の世界が次々と変わっていくのが不思議で面白いけど、話が少し難しいかも。",
        "content_warning": "銃撃戦などの暴力シーンがある。",
        "sf_review": "夢共有装置というガジェットを用いた、意識と現実の階層構造を描くSF。"
    },
    {
        "todo_title": "インターステラー",
        "title": "インターステラー",
        "original_title": "Interstellar",
        "filename": "Interstellar.md",
        "director": "クリストファー・ノーラン",
        "country": "アメリカ, イギリス",
        "release_year": 2014,
        "genre": ["SF", "ドラマ"],
        "rating_child": 3,
        "has_sexual_content": False,
        "has_violence": False,
        "sf_rating": 5,
        "synopsis": "食糧危機により人類滅亡の危機が迫る近未来。元宇宙飛行士のクーパーは、人類の移住先となる新たな惑星を探すため、愛する家族を残して宇宙の彼方へ旅立つ。",
        "recommendation": "宇宙の映像がとても綺麗。お父さんと娘の絆に感動する。",
        "content_warning": "特になし。",
        "sf_review": "ブラックホールや相対性理論など、最新の科学考証に基づいた本格SF。"
    },
    {
        "todo_title": "オデッセイ",
        "title": "オデッセイ",
        "original_title": "The Martian",
        "filename": "TheMartian.md",
        "director": "リドリー・スコット",
        "country": "アメリカ",
        "release_year": 2015,
        "genre": ["SF", "アドベンチャー", "ドラマ"],
        "rating_child": 4,
        "has_sexual_content": False,
        "has_violence": False,
        "sf_rating": 5,
        "synopsis": "火星探査中の事故で一人取り残された宇宙飛行士ワトニー。彼は限られた物資と科学知識を駆使して、火星でのサバイバル生活を送りながら地球への帰還を目指す。",
        "recommendation": "どんなに絶望的な状況でも、知恵とユーモアで乗り越える主人公がかっこいい！",
        "content_warning": "傷の手当てのシーンが少し痛々しい。",
        "sf_review": "火星でのサバイバル術が科学的に描かれており、見応え十分のSF。"
    },
    {
        "todo_title": "グラビティ",
        "title": "ゼロ・グラビティ",
        "original_title": "Gravity",
        "filename": "Gravity.md",
        "director": "アルフォンソ・キュアロン",
        "country": "アメリカ, イギリス",
        "release_year": 2013,
        "genre": ["SF", "サスペンス", "ドラマ"],
        "rating_child": 3,
        "has_sexual_content": False,
        "has_violence": False,
        "sf_rating": 5,
        "synopsis": "スペースシャトルの船外活動中に事故が発生し、宇宙空間に放り出されてしまったメディカル・エンジニアのライアン。酸素も残りわずかな極限状況の中、彼女は地球への生還を諦めずに戦う。",
        "recommendation": "宇宙に一人ぼっちになる怖さと、そこから頑張って帰ろうとする姿にドキドキする。",
        "content_warning": "事故のシーンが衝撃的。",
        "sf_review": "宇宙空間の無重力描写やデブリの恐怖がリアルに描かれたSFサバイバル。"
    },
    {
        "todo_title": "ブレードランナー 2049",
        "title": "ブレードランナー 2049",
        "original_title": "Blade Runner 2049",
        "filename": "BladeRunner2049.md",
        "director": "ドゥニ・ヴィルヌーヴ",
        "country": "アメリカ",
        "release_year": 2017,
        "genre": ["SF", "サスペンス"],
        "rating_child": 2,
        "has_sexual_content": True,
        "has_violence": True,
        "sf_rating": 5,
        "synopsis": "2049年、人造人間「レプリカント」を取り締まる捜査官「ブレードランナー」のKは、ある事件の捜査中に、社会を揺るがす重大な秘密を知ってしまう。",
        "recommendation": "未来の街並みが不思議で綺麗だけど、話が難しくて暗いかも。",
        "content_warning": "暴力シーンや裸のシーンがある。",
        "sf_review": "AIや人工生命の自我をテーマにした、サイバーパンクSFの金字塔の続編。"
    },
    {
        "todo_title": "2001年宇宙の旅",
        "title": "2001年宇宙の旅",
        "original_title": "2001: A Space Odyssey",
        "filename": "2001ASpaceOdyssey.md",
        "director": "スタンリー・キューブリック",
        "country": "イギリス, アメリカ",
        "release_year": 1968,
        "genre": ["SF"],
        "rating_child": 1,
        "has_sexual_content": False,
        "has_violence": True,
        "sf_rating": 5,
        "synopsis": "人類の進化を見守る謎の石板「モノリス」。木星探査に向かう宇宙船ディスカバリー号で、人工知能HAL9000が反乱を起こす。",
        "recommendation": "映像はすごいけど、セリフが少なくて意味がわからないかもしれない。",
        "content_warning": "特になしだが、AIの行動が不気味。",
        "sf_review": "SF映画の金字塔。AIの反乱や人類の進化を哲学的かつ映像美豊かに描く。"
    },
    {
        "todo_title": "メン・イン・ブラック",
        "title": "メン・イン・ブラック",
        "original_title": "Men in Black",
        "filename": "MenInBlack.md",
        "director": "バリー・ソネンフェルド",
        "country": "アメリカ",
        "release_year": 1997,
        "genre": ["SF", "アクション", "コメディ"],
        "rating_child": 4,
        "has_sexual_content": False,
        "has_violence": True,
        "sf_rating": 5,
        "synopsis": "地球に生息するエイリアンを監視する秘密組織MIB。新米エージェントのJはベテランのKとコンビを組み、地球の平和を守るために戦う。",
        "recommendation": "変な宇宙人がたくさん出てきて面白い！JとKのやり取りも笑える。",
        "content_warning": "エイリアンが破裂したりするシーンが少しグロテスクかも。",
        "sf_review": "宇宙人が日常に紛れているという設定と、記憶消去装置などのガジェットが楽しいSFアクション。"
    },
    {
        "todo_title": "ゴーストバスターズ",
        "title": "ゴーストバスターズ",
        "original_title": "Ghostbusters",
        "filename": "Ghostbusters.md",
        "director": "アイヴァン・ライトマン",
        "country": "アメリカ",
        "release_year": 1984,
        "genre": ["SF", "コメディ", "ホラー"],
        "rating_child": 4,
        "has_sexual_content": False,
        "has_violence": False,
        "sf_rating": 4,
        "synopsis": "ニューヨークで幽霊退治業を始めた科学者たち。彼らはプロトンパックというハイテク装備を背負い、街に現れるゴーストたちを捕獲していく。",
        "recommendation": "お化け退治が楽しそう！マシュマロマンが可愛い。",
        "content_warning": "お化けが少し怖いかもしれない。",
        "sf_review": "科学の力で霊的現象に対処するという設定がユニークなSFコメディ。"
    },
    {
        "todo_title": "アベンジャーズ",
        "title": "アベンジャーズ",
        "original_title": "The Avengers",
        "filename": "TheAvengers.md",
        "director": "ジョス・ウェドン",
        "country": "アメリカ",
        "release_year": 2012,
        "genre": ["アクション", "SF", "ヒーロー"],
        "rating_child": 4,
        "has_sexual_content": False,
        "has_violence": True,
        "sf_rating": 4,
        "synopsis": "地球侵略の危機に、アイアンマン、キャプテン・アメリカ、ソー、ハルクら最強のヒーローたちが集結。チーム「アベンジャーズ」として団結し、敵に立ち向かう。",
        "recommendation": "いろんなヒーローが勢揃いして戦うのがとにかくかっこいい！",
        "content_warning": "激しい戦闘シーンがある。",
        "sf_review": "ハイテク装備や宇宙からの侵略者など、SF要素満載のスーパーヒーロー映画。"
    },
    {
        "todo_title": "アイアンマン",
        "title": "アイアンマン",
        "original_title": "Iron Man",
        "filename": "IronMan.md",
        "director": "ジョン・ファヴロー",
        "country": "アメリカ",
        "release_year": 2008,
        "genre": ["アクション", "SF", "ヒーロー"],
        "rating_child": 4,
        "has_sexual_content": False,
        "has_violence": True,
        "sf_rating": 5,
        "synopsis": "巨大軍事企業の社長トニー・スタークは、テロリストに拉致されたことをきっかけに、自ら開発したパワードスーツを装着し「アイアンマン」として悪と戦うことを決意する。",
        "recommendation": "主人公が自分でスーツを作って変身するのがかっこいい！",
        "content_warning": "戦闘シーンがある。",
        "sf_review": "パワードスーツのメカニック描写や開発プロセスが詳細に描かれたSFアクション。"
    },
    {
        "todo_title": "スパイダーマン",
        "title": "スパイダーマン",
        "original_title": "Spider-Man",
        "filename": "SpiderMan.md",
        "director": "サム・ライミ",
        "country": "アメリカ",
        "release_year": 2002,
        "genre": ["アクション", "SF", "ヒーロー"],
        "rating_child": 4,
        "has_sexual_content": False,
        "has_violence": True,
        "sf_rating": 3,
        "synopsis": "特殊なクモに噛まれて超能力を得た高校生ピーター・パーカー。彼はその力を正義のために使うことを誓い、スパイダーマンとしてニューヨークの街を守る。",
        "recommendation": "ビルからビルへ糸で飛び移るシーンが気持ちよさそう！",
        "content_warning": "敵のグリーン・ゴブリンが少し怖い。",
        "sf_review": "遺伝子操作されたクモによる能力獲得など、バイオSF的な要素を含むヒーロー映画。"
    },
    {
        "todo_title": "ダークナイト",
        "title": "ダークナイト",
        "original_title": "The Dark Knight",
        "filename": "TheDarkKnight.md",
        "director": "クリストファー・ノーラン",
        "country": "アメリカ, イギリス",
        "release_year": 2008,
        "genre": ["アクション", "クライム", "ドラマ"],
        "rating_child": 2,
        "has_sexual_content": False,
        "has_violence": True,
        "sf_rating": 2,
        "synopsis": "ゴッサム・シティに現れた最凶の犯罪者ジョーカー。バットマンは彼を止めるために奔走するが、ジョーカーの狂気は街の人々を恐怖と混乱に陥れていく。",
        "recommendation": "バットマンはかっこいいけど、敵のジョーカーが怖すぎるし、話が暗い。",
        "content_warning": "暴力シーンや残酷な描写が多い。",
        "sf_review": "ハイテクガジェットは登場するが、よりリアルな犯罪ドラマとしての側面が強い。"
    },
    {
        "todo_title": "ジョーカー",
        "title": "ジョーカー",
        "original_title": "Joker",
        "filename": "Joker.md",
        "director": "トッド・フィリップス",
        "country": "アメリカ",
        "release_year": 2019,
        "genre": ["ドラマ", "スリラー"],
        "rating_child": 1,
        "has_sexual_content": False,
        "has_violence": True,
        "sf_rating": 1,
        "synopsis": "孤独で心優しい大道芸人のアーサーは、社会から疎外され、次第に狂気へと堕ちていく。やがて彼は悪のカリスマ「ジョーカー」へと変貌を遂げる。",
        "recommendation": "怖くて悲しいお話なので、小学生にはおすすめできない。",
        "content_warning": "暴力表現や精神的に重い描写がある。",
        "sf_review": "SF要素はない。社会派ドラマ。"
    },
    {
        "todo_title": "ワンダーウーマン",
        "title": "ワンダーウーマン",
        "original_title": "Wonder Woman",
        "filename": "WonderWoman.md",
        "director": "パティ・ジェンキンス",
        "country": "アメリカ",
        "release_year": 2017,
        "genre": ["アクション", "ファンタジー", "ヒーロー"],
        "rating_child": 4,
        "has_sexual_content": False,
        "has_violence": True,
        "sf_rating": 1,
        "synopsis": "女性だけの島で育った王女ダイアナ。外の世界で戦争が起きていることを知り、世界を救うために島を出て戦士ワンダーウーマンとして立ち上がる。",
        "recommendation": "強くて美しいワンダーウーマンがかっこいい！",
        "content_warning": "戦争のシーンがある。",
        "sf_review": "神話ベースのファンタジーアクション。"
    },
    {
        "todo_title": "ミッション:インポッシブル",
        "title": "ミッション:インポッシブル",
        "original_title": "Mission: Impossible",
        "filename": "MissionImpossible.md",
        "director": "ブライアン・デ・パルマ",
        "country": "アメリカ",
        "release_year": 1996,
        "genre": ["アクション", "スパイ"],
        "rating_child": 3,
        "has_sexual_content": False,
        "has_violence": True,
        "sf_rating": 2,
        "synopsis": "極秘スパイ組織IMFのエージェント、イーサン・ハント。裏切り者の汚名を着せられた彼は、真犯人を見つけ出すために不可能に近いミッションに挑む。",
        "recommendation": "宙吊りになったり変装したり、スパイの活動にドキドキする！",
        "content_warning": "暴力シーンがある。",
        "sf_review": "ハイテクスパイガジェットが登場するが、基本はアクション。"
    },
    {
        "todo_title": "007 カジノ・ロワイヤル",
        "title": "007 カジノ・ロワイヤル",
        "original_title": "Casino Royale",
        "filename": "CasinoRoyale.md",
        "director": "マーティン・キャンベル",
        "country": "イギリス, アメリカ",
        "release_year": 2006,
        "genre": ["アクション", "スパイ"],
        "rating_child": 2,
        "has_sexual_content": True,
        "has_violence": True,
        "sf_rating": 2,
        "synopsis": "英国諜報部員ジェームズ・ボンドが「007」の称号を得て最初の任務に挑む。テロ組織の資金源を断つため、カジノでのポーカー勝負に挑む。",
        "recommendation": "大人のアクション映画なので、小学生には少し早いかも。",
        "content_warning": "拷問シーンなどが痛々しい。",
        "sf_review": "スパイガジェットは控えめで、リアルなアクション重視。"
    },
    {
        "todo_title": "キングスマン",
        "title": "キングスマン",
        "original_title": "Kingsman: The Secret Service",
        "filename": "KingsmanTheSecretService.md",
        "director": "マシュー・ヴォーン",
        "country": "イギリス, アメリカ",
        "release_year": 2014,
        "genre": ["アクション", "スパイ", "コメディ"],
        "rating_child": 2,
        "has_sexual_content": True,
        "has_violence": True,
        "sf_rating": 2,
        "synopsis": "ロンドンの高級テーラーの裏にある独立スパイ機関「キングスマン」。不良少年のエグジーは、エージェントのハリーに見出され、過酷な訓練を経てスパイを目指す。",
        "recommendation": "アクションはすごいけど、人がたくさん死ぬし下品なジョークもあるので注意。",
        "content_warning": "過激な暴力描写（頭が爆発するなど）や性的表現がある。",
        "sf_review": "傘型銃などのユニークなガジェットが登場するスパイアクション。"
    },
    {
        "todo_title": "マッドマックス 怒りのデス・ロード",
        "title": "マッドマックス 怒りのデス・ロード",
        "original_title": "Mad Max: Fury Road",
        "filename": "MadMaxFuryRoad.md",
        "director": "ジョージ・ミラー",
        "country": "オーストラリア, アメリカ",
        "release_year": 2015,
        "genre": ["アクション", "SF"],
        "rating_child": 2,
        "has_sexual_content": False,
        "has_violence": True,
        "sf_rating": 3,
        "synopsis": "荒廃した近未来。独裁者に支配された砦から逃走した女性戦士フュリオサと、それに巻き込まれた元警官のマックス。彼らは改造車を駆り、追っ手との激しい逃走劇を繰り広げる。",
        "recommendation": "車のアクションがすごいけど、世界観が怖くて暴力的。",
        "content_warning": "激しい暴力シーンやグロテスクな表現がある。",
        "sf_review": "文明崩壊後の世界を描いたポストアポカリプスSF。"
    },
    {
        "todo_title": "ジョン・ウィック",
        "title": "ジョン・ウィック",
        "original_title": "John Wick",
        "filename": "JohnWick.md",
        "director": "チャド・スタエルスキ",
        "country": "アメリカ",
        "release_year": 2014,
        "genre": ["アクション"],
        "rating_child": 1,
        "has_sexual_content": False,
        "has_violence": True,
        "sf_rating": 1,
        "synopsis": "伝説の殺し屋ジョン・ウィックは、亡き妻が遺した子犬をマフィアに殺され、復讐のために裏社会に戻ってくる。",
        "recommendation": "ひたすら人が撃たれるので、小学生にはおすすめできない。",
        "content_warning": "銃撃戦で大量に人が死ぬ。",
        "sf_review": "SF要素はない。"
    },
    {
        "todo_title": "ダイ・ハード",
        "title": "ダイ・ハード",
        "original_title": "Die Hard",
        "filename": "DieHard.md",
        "director": "ジョン・マクティアナン",
        "country": "アメリカ",
        "release_year": 1988,
        "genre": ["アクション"],
        "rating_child": 3,
        "has_sexual_content": False,
        "has_violence": True,
        "sf_rating": 1,
        "synopsis": "クリスマス・イブ、高層ビルがテロリストに占拠された。たまたま居合わせた刑事ジョン・マクレーンは、たった一人で武装集団に立ち向かう。",
        "recommendation": "マクレーン刑事がボロボロになりながら頑張る姿がかっこいい！",
        "content_warning": "銃撃戦や爆発シーン、血が出るシーンがある。",
        "sf_review": "SF要素はない。"
    },
    {
        "todo_title": "ターミネーター2",
        "title": "ターミネーター2",
        "original_title": "Terminator 2: Judgment Day",
        "filename": "Terminator2JudgmentDay.md",
        "director": "ジェームズ・キャメロン",
        "country": "アメリカ",
        "release_year": 1991,
        "genre": ["SF", "アクション"],
        "rating_child": 3,
        "has_sexual_content": False,
        "has_violence": True,
        "sf_rating": 5,
        "synopsis": "未来から送り込まれた新型ターミネーターT-1000に命を狙われる少年ジョン。彼を守るために現れたのは、かつて母を襲った旧型ターミネーターT-800だった。",
        "recommendation": "敵のターミネーターがどんなに変形しても追いかけてきて怖い！でも味方のターミネーターは頼りになる。",
        "content_warning": "銃撃戦や体が突き刺さるシーンなどがある。",
        "sf_review": "液体金属などのVFX技術とタイムトラベル設定が秀逸なSFアクション。"
    },
    {
        "todo_title": "レオン",
        "title": "レオン",
        "original_title": "Léon: The Professional",
        "filename": "LeonTheProfessional.md",
        "director": "リュック・ベッソン",
        "country": "フランス, アメリカ",
        "release_year": 1994,
        "genre": ["アクション", "ドラマ"],
        "rating_child": 2,
        "has_sexual_content": False,
        "has_violence": True,
        "sf_rating": 1,
        "synopsis": "孤独な殺し屋レオンと、麻薬捜査官に家族を殺された少女マチルダ。奇妙な共同生活を始めた二人は、次第に心を通わせていく。",
        "recommendation": "切ない物語だけど、殺し屋の話なので暴力的。",
        "content_warning": "家族が殺されるシーンなどが残酷。",
        "sf_review": "SF要素はない。"
    },
    {
        "todo_title": "トップガン マーヴェリック",
        "title": "トップガン マーヴェリック",
        "original_title": "Top Gun: Maverick",
        "filename": "TopGunMaverick.md",
        "director": "ジョセフ・コシンスキー",
        "country": "アメリカ",
        "release_year": 2022,
        "genre": ["アクション", "ドラマ"],
        "rating_child": 4,
        "has_sexual_content": False,
        "has_violence": False,
        "sf_rating": 1,
        "synopsis": "アメリカ海軍のエリートパイロット養成校「トップガン」に教官として帰ってきた伝説のパイロット、マーヴェリック。彼は若きパイロットたちと共に、困難な極秘任務に挑む。",
        "recommendation": "戦闘機が空を飛ぶシーンが大迫力でスカッとする！",
        "content_warning": "特になし。",
        "sf_review": "最新鋭の戦闘機が登場するが、舞台は現実世界。"
    },
    {
        "todo_title": "タイタニック",
        "title": "タイタニック",
        "original_title": "Titanic",
        "filename": "Titanic.md",
        "director": "ジェームズ・キャメロン",
        "country": "アメリカ",
        "release_year": 1997,
        "genre": ["ロマンス", "ドラマ", "パニック"],
        "rating_child": 3,
        "has_sexual_content": True,
        "has_violence": False,
        "sf_rating": 1,
        "synopsis": "豪華客船タイタニック号で出会った、貧しい青年ジャックと上流階級の娘ローズ。二人は身分違いの恋に落ちるが、船は氷山に衝突し、沈没の時が迫る。",
        "recommendation": "ロマンチックだけど、最後は悲しい。船が沈むシーンは怖くてドキドキする。",
        "content_warning": "ヌードデッサンのシーンで裸が出る。",
        "sf_review": "SF要素はない。"
    },
    {
        "todo_title": "ラ・ラ・ランド",
        "title": "ラ・ラ・ランド",
        "original_title": "La La Land",
        "filename": "LaLaLand.md",
        "director": "デイミアン・チャゼル",
        "country": "アメリカ",
        "release_year": 2016,
        "genre": ["ミュージカル", "ロマンス"],
        "rating_child": 4,
        "has_sexual_content": False,
        "has_violence": False,
        "sf_rating": 1,
        "synopsis": "夢を追う女優の卵ミアと、ジャズピアニストのセバスチャン。ロサンゼルスで出会った二人は恋に落ち、互いに夢を応援し合うが、成功と共にすれ違いが生まれる。",
        "recommendation": "歌とダンスが素敵で、衣装もカラフルで可愛い！",
        "content_warning": "特になし。",
        "sf_review": "SF要素はない。"
    },
    {
        "todo_title": "グレイテスト・ショーマン",
        "title": "グレイテスト・ショーマン",
        "original_title": "The Greatest Showman",
        "filename": "TheGreatestShowman.md",
        "director": "マイケル・グレイシー",
        "country": "アメリカ",
        "release_year": 2017,
        "genre": ["ミュージカル", "ドラマ"],
        "rating_child": 5,
        "has_sexual_content": False,
        "has_violence": False,
        "sf_rating": 1,
        "synopsis": "19世紀のアメリカ。アイデアマンのバーナムは、個性的な人々を集めたショーを立ち上げ、大成功を収める。しかし、その裏で様々な困難や差別にも直面する。",
        "recommendation": "サーカスのショーがキラキラしていて楽しい！歌も元気が出る。",
        "content_warning": "特になし。",
        "sf_review": "SF要素はない。"
    },
    {
        "todo_title": "ボヘミアン・ラプソディ",
        "title": "ボヘミアン・ラプソディ",
        "original_title": "Bohemian Rhapsody",
        "filename": "BohemianRhapsody.md",
        "director": "ブライアン・シンガー",
        "country": "イギリス, アメリカ",
        "release_year": 2018,
        "genre": ["ドラマ", "音楽"],
        "rating_child": 3,
        "has_sexual_content": True,
        "has_violence": False,
        "sf_rating": 1,
        "synopsis": "伝説のロックバンド「クイーン」のボーカル、フレディ・マーキュリーの波乱の人生を描く。名曲誕生の裏側や、孤独との戦い、そして圧巻のライブ・エイドでのパフォーマンスまで。",
        "recommendation": "知っている曲がたくさん流れて楽しい！",
        "content_warning": "同性愛描写やキスシーンがある。",
        "sf_review": "SF要素はない。"
    },
    {
        "todo_title": "ホーム・アローン",
        "title": "ホーム・アローン",
        "original_title": "Home Alone",
        "filename": "HomeAlone.md",
        "director": "クリス・コロンバス",
        "country": "アメリカ",
        "release_year": 1990,
        "genre": ["コメディ", "ファミリー"],
        "rating_child": 5,
        "has_sexual_content": False,
        "has_violence": False,
        "sf_rating": 1,
        "synopsis": "クリスマスに家族旅行に置いてきぼりにされた8歳のケビン。一人暮らしを満喫していたが、泥棒二人組が家を狙っていることに気づき、家中の仕掛けを使って撃退する。",
        "recommendation": "ケビンが泥棒をやっつける仕掛けが面白くて大爆笑！",
        "content_warning": "特になし。",
        "sf_review": "SF要素はない。"
    },
    {
        "todo_title": "チャーリーとチョコレート工場",
        "title": "チャーリーとチョコレート工場",
        "original_title": "Charlie and the Chocolate Factory",
        "filename": "CharlieAndTheChocolateFactory.md",
        "director": "ティム・バートン",
        "country": "アメリカ, イギリス",
        "release_year": 2005,
        "genre": ["ファンタジー", "コメディ"],
        "rating_child": 4,
        "has_sexual_content": False,
        "has_violence": False,
        "sf_rating": 1,
        "synopsis": "謎の工場長ウィリー・ウォンカが経営する巨大なチョコレート工場。黄金のチケットを引き当てたチャーリーら5人の子供たちが工場見学に招かれる。",
        "recommendation": "お菓子でできた世界が夢みたい！でもちょっと変で不気味なところもある。",
        "content_warning": "悪い子供たちがひどい目に遭うシーンが少し怖いかも。",
        "sf_review": "不思議な発明品が登場するファンタジー。"
    },
    {
        "todo_title": "スタンド・バイ・ミー",
        "title": "スタンド・バイ・ミー",
        "original_title": "Stand by Me",
        "filename": "StandByMe.md",
        "director": "ロブ・ライナー",
        "country": "アメリカ",
        "release_year": 1986,
        "genre": ["ドラマ", "アドベンチャー"],
        "rating_child": 3,
        "has_sexual_content": False,
        "has_violence": False,
        "sf_rating": 1,
        "synopsis": "12歳の少年4人が、行方不明になった少年の死体を探しに旅に出る。線路の上を歩きながら、彼らは悩みや秘密を語り合い、友情を深めていく。",
        "recommendation": "子供たちだけの冒険に憧れる。でも死体を探す話なのでちょっと怖い。",
        "content_warning": "死体が出てくる。タバコを吸うシーンがある。",
        "sf_review": "SF要素はない。"
    },
    {
        "todo_title": "ショーシャンクの空に",
        "title": "ショーシャンクの空に",
        "original_title": "The Shawshank Redemption",
        "filename": "TheShawshankRedemption.md",
        "director": "フランク・ダラボン",
        "country": "アメリカ",
        "release_year": 1994,
        "genre": ["ドラマ"],
        "rating_child": 2,
        "has_sexual_content": True,
        "has_violence": True,
        "sf_rating": 1,
        "synopsis": "無実の罪で刑務所に送られた銀行員アンディ。過酷な環境の中でも希望を捨てず、知恵と誠実さで周囲の信頼を勝ち取り、自由への道を切り開いていく。",
        "recommendation": "感動的な話だけど、刑務所の中が怖くて暗い。",
        "content_warning": "暴力やレイプを示唆するシーンがある。",
        "sf_review": "SF要素はない。"
    },
    {
        "todo_title": "フォレスト・ガンプ/一期一会",
        "title": "フォレスト・ガンプ/一期一会",
        "original_title": "Forrest Gump",
        "filename": "ForrestGump.md",
        "director": "ロバート・ゼメキス",
        "country": "アメリカ",
        "release_year": 1994,
        "genre": ["ドラマ", "ロマンス"],
        "rating_child": 4,
        "has_sexual_content": True,
        "has_violence": True,
        "sf_rating": 1,
        "synopsis": "知能指数は低いが純粋な心を持つフォレスト・ガンプ。激動のアメリカ現代史の中を駆け抜けながら、多くの人々と関わり、奇跡のような人生を歩んでいく。",
        "recommendation": "主人公がひたむきに頑張る姿に感動する。",
        "content_warning": "戦争のシーンがある。",
        "sf_review": "SF要素はない。"
    },
    {
        "todo_title": "グリーンブック",
        "title": "グリーンブック",
        "original_title": "Green Book",
        "filename": "GreenBook.md",
        "director": "ピーター・ファレリー",
        "country": "アメリカ",
        "release_year": 2018,
        "genre": ["ドラマ", "コメディ"],
        "rating_child": 3,
        "has_sexual_content": False,
        "has_violence": True,
        "sf_rating": 1,
        "synopsis": "人種差別が色濃く残る1960年代のアメリカ南部。黒人天才ピアニストと、その運転手兼用心棒として雇われた粗野な白人男性が、コンサートツアーの旅に出る。",
        "recommendation": "正反対の二人が仲良くなっていくのが素敵。",
        "content_warning": "差別的な表現や暴力シーンがある。",
        "sf_review": "SF要素はない。"
    },
    {
        "todo_title": "最強のふたり",
        "title": "最強のふたり",
        "original_title": "The Intouchables",
        "filename": "TheIntouchables.md",
        "director": "エリック・トレダノ, オリヴィエ・ナカシュ",
        "country": "フランス",
        "release_year": 2011,
        "genre": ["ドラマ", "コメディ"],
        "rating_child": 3,
        "has_sexual_content": False,
        "has_violence": False,
        "sf_rating": 1,
        "synopsis": "事故で全身麻痺となった大富豪フィリップと、その介護人として雇われたスラム街出身の青年ドリス。境遇も性格も全く違う二人が、本音でぶつかり合いながら深い友情を築いていく。",
        "recommendation": "笑って泣ける友情物語。",
        "content_warning": "特になし。",
        "sf_review": "SF要素はない。"
    },
    {
        "todo_title": "ライフ・イズ・ビューティフル",
        "title": "ライフ・イズ・ビューティフル",
        "original_title": "Life Is Beautiful",
        "filename": "LifeIsBeautiful.md",
        "director": "ロベルト・ベニーニ",
        "country": "イタリア",
        "release_year": 1997,
        "genre": ["ドラマ", "コメディ", "戦争"],
        "rating_child": 3,
        "has_sexual_content": False,
        "has_violence": True,
        "sf_rating": 1,
        "synopsis": "第二次世界大戦下の強制収容所。ユダヤ系イタリア人のグイドは、幼い息子を怖がらせないため、収容所生活を「ゲーム」だと言って嘘をつき通し、命がけで守り抜く。",
        "recommendation": "お父さんの愛にすごく感動するけど、戦争の話なので悲しい。",
        "content_warning": "戦争や強制収容所の描写がある。",
        "sf_review": "SF要素はない。"
    },
    {
        "todo_title": "ニュー・シネマ・パラダイス",
        "title": "ニュー・シネマ・パラダイス",
        "original_title": "Cinema Paradiso",
        "filename": "CinemaParadiso.md",
        "director": "ジュゼッペ・トルナトーレ",
        "country": "イタリア, フランス",
        "release_year": 1988,
        "genre": ["ドラマ"],
        "rating_child": 3,
        "has_sexual_content": True,
        "has_violence": False,
        "sf_rating": 1,
        "synopsis": "シチリア島の小さな村。映画好きの少年トトは、映画館の映写技師アルフレードと親子のような友情を育む。成長したトトは映画監督となり、故郷を振り返る。",
        "recommendation": "映画が大好きな男の子の話。昔の映画館の雰囲気が素敵。",
        "content_warning": "キスシーンを集めた映像などが流れる。",
        "sf_review": "SF要素はない。"
    },
    {
        "todo_title": "ゴッドファーザー",
        "title": "ゴッドファーザー",
        "original_title": "The Godfather",
        "filename": "TheGodfather.md",
        "director": "フランシス・フォード・コッポラ",
        "country": "アメリカ",
        "release_year": 1972,
        "genre": ["クライム", "ドラマ"],
        "rating_child": 1,
        "has_sexual_content": True,
        "has_violence": True,
        "sf_rating": 1,
        "synopsis": "イタリア系マフィアのコルレオーネ・ファミリーの興亡を描く壮大なドラマ。家長のヴィトーとその息子マイケルを中心に、裏社会の権力争いと家族の絆が描かれる。",
        "recommendation": "マフィアの怖い話なので、小学生にはおすすめできない。",
        "content_warning": "殺人のシーンや暴力描写が多い。",
        "sf_review": "SF要素はない。"
    },
    {
        "todo_title": "パルプ・フィクション",
        "title": "パルプ・フィクション",
        "original_title": "Pulp Fiction",
        "filename": "PulpFiction.md",
        "director": "クエンティン・タランティーノ",
        "country": "アメリカ",
        "release_year": 1994,
        "genre": ["クライム", "ドラマ"],
        "rating_child": 1,
        "has_sexual_content": True,
        "has_violence": True,
        "sf_rating": 1,
        "synopsis": "二人のギャング、ボクサー、ギャングのボスとその妻など、一見無関係な人々の一連の出来事が、時間軸を交差させながら奇妙に繋がっていく。",
        "recommendation": "話がバラバラで難しく、暴力的なので小学生にはおすすめできない。",
        "content_warning": "薬物の使用や暴力、性的な話が多い。",
        "sf_review": "SF要素はない。"
    },
    {
        "todo_title": "セブン",
        "title": "セブン",
        "original_title": "Seven",
        "filename": "Seven.md",
        "director": "デヴィッド・フィンチャー",
        "country": "アメリカ",
        "release_year": 1995,
        "genre": ["サスペンス", "クライム"],
        "rating_child": 1,
        "has_sexual_content": True,
        "has_violence": True,
        "sf_rating": 1,
        "synopsis": "「七つの大罪」に見立てた連続猟奇殺人事件が発生。退職間近のベテラン刑事と血気盛んな新米刑事のコンビが、犯人を追って雨の降り続く街を奔走する。",
        "recommendation": "とても怖くて気持ち悪い事件の話なので、小学生には絶対におすすめできない。",
        "content_warning": "死体がグロテスクで、内容も非常に暗い。",
        "sf_review": "SF要素はない。"
    },
    {
        "todo_title": "ファイト・クラブ",
        "title": "ファイト・クラブ",
        "original_title": "Fight Club",
        "filename": "FightClub.md",
        "director": "デヴィッド・フィンチャー",
        "country": "アメリカ",
        "release_year": 1999,
        "genre": ["ドラマ", "サスペンス"],
        "rating_child": 1,
        "has_sexual_content": True,
        "has_violence": True,
        "sf_rating": 1,
        "synopsis": "不眠症に悩む平凡な会社員は、謎の男タイラーと出会い、殴り合いで鬱屈を発散する秘密組織「ファイト・クラブ」を結成する。組織は次第に過激化し、制御不能になっていく。",
        "recommendation": "暴力的なので小学生にはおすすめできない。",
        "content_warning": "激しい暴力シーンや性的な描写がある。",
        "sf_review": "SF要素はない。"
    },
    {
        "todo_title": "プラダを着た悪魔",
        "title": "プラダを着た悪魔",
        "original_title": "The Devil Wears Prada",
        "filename": "TheDevilWearsPrada.md",
        "director": "デヴィッド・フランケル",
        "country": "アメリカ",
        "release_year": 2006,
        "genre": ["ドラマ", "コメディ"],
        "rating_child": 4,
        "has_sexual_content": False,
        "has_violence": False,
        "sf_rating": 1,
        "synopsis": "ジャーナリスト志望のアンディは、一流ファッション誌の編集部で働くことになる。しかし、彼女の上司は無理難題を押し付ける悪魔のような編集長ミランダだった。",
        "recommendation": "おしゃれな服がたくさん出てきて楽しい！仕事に頑張る姿にかっこいい。",
        "content_warning": "特になし。",
        "sf_review": "SF要素はない。"
    },
    {
        "todo_title": "マイ・インターン",
        "title": "マイ・インターン",
        "original_title": "The Intern",
        "filename": "TheIntern.md",
        "director": "ナンシー・マイヤーズ",
        "country": "アメリカ",
        "release_year": 2015,
        "genre": ["ドラマ", "コメディ"],
        "rating_child": 4,
        "has_sexual_content": False,
        "has_violence": False,
        "sf_rating": 1,
        "synopsis": "ファッション通販サイトを運営する若き女社長ジュールズの元に、70歳のシニア・インターン、ベンがやってくる。最初は煙たがっていたジュールズだが、ベンの人生経験と優しさに助けられていく。",
        "recommendation": "おじいちゃんが優しくて素敵。仕事や友達の大切さがわかる。",
        "content_warning": "特になし。",
        "sf_review": "SF要素はない。"
    },
    {
        "todo_title": "英国王のスピーチ",
        "title": "英国王のスピーチ",
        "original_title": "The King's Speech",
        "filename": "TheKingsSpeech.md",
        "director": "トム・フーパー",
        "country": "イギリス, オーストラリア",
        "release_year": 2010,
        "genre": ["ドラマ", "歴史"],
        "rating_child": 3,
        "has_sexual_content": False,
        "has_violence": False,
        "sf_rating": 1,
        "synopsis": "吃音に悩む英国王ジョージ6世。国民を勇気づけるスピーチを行うため、言語聴覚士のライオネルと共に治療に励み、コンプレックスを克服しようとする。",
        "recommendation": "王様が苦手を克服しようと頑張る姿に勇気をもらえる。",
        "content_warning": "特になし。",
        "sf_review": "SF要素はない。"
    }
]

def create_movie_file(movie):
    filepath = os.path.join("Movie", movie["filename"])
    if os.path.exists(filepath):
        print(f"File already exists: {filepath}")
        return

    content = f"""---
title: "{movie['title']}"
original_title: "{movie['original_title']}"
director: "{movie['director']}"
country: "{movie['country']}"
release_year: {movie['release_year']}
genre: {str(movie['genre']).replace("'", '"')}
rating_child: {movie['rating_child']}
has_sexual_content: {str(movie['has_sexual_content']).lower()}
has_violence: {str(movie['has_violence']).lower()}
sf_rating: {movie['sf_rating']}
---

## あらすじ
{movie['synopsis']}

## おすすめポイント（小学生女児基準）
{movie['recommendation']}

## エロ/グロ表現（小学生女児基準）
{movie['content_warning']}

## SF的な要素とその評価
{movie['sf_review']}
"""
    with open(filepath, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"Created: {filepath}")

def update_todo(movies):
    todo_path = "TODO.md"
    with open(todo_path, "r", encoding="utf-8") as f:
        lines = f.readlines()

    new_lines = []
    updated_count = 0

    # Create a set of processed titles for quick lookup
    processed_titles = {m["todo_title"] for m in movies}

    for line in lines:
        stripped = line.strip()
        matched = False
        if "[ ]" in stripped:
            title_part = stripped.split("]")[1].strip()
            # Handle potential trailing/leading spaces or slight mismatches if needed
            if title_part in processed_titles:
                new_lines.append(line.replace("[ ]", "[x]"))
                updated_count += 1
                matched = True

        if not matched:
            new_lines.append(line)

    with open(todo_path, "w", encoding="utf-8") as f:
        f.writelines(new_lines)
    print(f"Updated TODO.md: {updated_count} items marked as checked.")

def main():
    # Ensure Movie directory exists
    if not os.path.exists("Movie"):
        os.makedirs("Movie")

    for movie in movies_data:
        create_movie_file(movie)
    update_todo(movies_data)

if __name__ == "__main__":
    main()
